# Generated by Django 4.1.2 on 2022-12-06 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="banking_changes",
            name="gain_loss",
            field=models.BooleanField(null=True),
        ),
    ]
