# Generated by Django 4.1.1 on 2022-12-02 20:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0002_remove_stock_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="banking_changes",
            name="name",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="stock",
            name="date",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="banking_changes",
            name="date_added",
            field=models.DateTimeField(
                blank=True, default=datetime.datetime.now, null=True
            ),
        ),
    ]
